### ISSUE TITLE
Composer Support?

### ISSUE THREAD

**Issue by media-arts** [heisenbol/skjsonlylightbox#1]
Hello,

is it possible to make your extension compatible for composer support?

Thanks, best regards

Media Arts

**Comment by heisenbol** [comment]
this is on my todo list for a very long time. I'll take this issue as an opportunity to implement it. I expect sometime within the next 2 weeks

**Comment by media-arts** [comment]
that would be great   ;o)

**Comment by heisenbol** [comment]
Added composer support with version 0.4.0

**Comment by media-arts** [comment]
Many thanks for that.

One thing is still missing. The addition of the Composer line on the extension page here.
https://extensions.typo3.org/extension/skjsonlylightbox




As with the news extension
![grafik](https://github.com/sksksksk/skjsonlylightbox/assets/32893751/3bbba061-c79d-4248-b6c5-0a48900161ce)

**Comment by heisenbol** [comment]
> Many thanks for that.
> 
> One thing is still missing. The addition of the Composer line on the extension page here. https://extensions.typo3.org/extension/skjsonlylightbox
> 
a, yes. Thanks for that! Fixed
